### ISSUE TITLE
Creating a readme.md for the project.

### ISSUE THREAD

**Issue by 1Shubham7** [1Shubham7/ChaCha-GPT#1]

**Comment by Abraham12611** [comment]
Hello, I am willing to help create an explicit README for your project.

But i might need a little bit more information on the project.

**Comment by 1Shubham7** [comment]
Ok. so the project is about a fun Chat GPT clone. It is using OpenAI API. Project is not deployed yet because Open AI provides a little free credits to use. Project is created with Django + HTML + CSS + JS. you can add about how to contribute, star the repo, and make the readme fun. ChaCha GPT is open for contributions.

**Comment by 1Shubham7** [comment]
@Abraham12611  you can create a short readme with this much information. Your contributions are much appreciated.

**Comment by Abraham12611** [comment]
Okay would start working on it.

**Comment by Jimike110** [comment]
Mind if I contribute?

**Comment by 1Shubham7** [comment]
No, @Jimike. But it would be better you contribute to https://github.com/1Shubham7/Wife-Predictor . I will assign you the issue there. I can do that?

**Comment by Jimike110** [comment]
Sure

**Comment by 1Shubham7** [comment]
You can go and check the issue and comment below. I will assign it to you.

**Comment by Abraham12611** [comment]
I have created a pull request.
If you want anything changed, I am open to make those changes.

**Comment by Abraham12611** [comment]
I am glad you like it 👍
